### ISSUE TITLE
can not close StringUniqueKeyFormatter and MorphlineResultToSolrMapper

### ISSUE THREAD

**Issue by syzxlyx** [NGDATA/hbase-indexer#70]
When my hbase-indexer stop,it will call closer.close() .but the classes have not close() mothod.
why?
15/12/16 10:21:48 ERROR io.Closer: Do not know how to close object of type com.ngdata.hbaseindexer.morphline.MorphlineResultToSolrMapper
15/12/16 10:21:48 ERROR io.Closer: Do not know how to close object of type com.ngdata.hbaseindexer.uniquekey.StringUniqueKeyFormatter

**Comment by gabrielreid** [comment]
Some ResultToSolrMapper and KeyFormatter implementations implement the Closeable interface, but these two interfaces do no extend the Closeable interface themselves. These objects are passed in to a Closer instance, which attempts to close them if they implement Closeable, and logs this message if the instances are not Closeable. 

In other words, there is nothing to worry about here, although it might be better if those were warning logging messages instead of errors.
